//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaSalas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reservacion
    {
        public int IDReservacion { get; set; }
        public int IDSala { get; set; }
        public int IDUsuario { get; set; }


        [Display(Name = "Asunto")]
        public string DescReserv { get; set; }

        [Display(Name = "Hora Inicio")]
        public Nullable<System.DateTime> DTInicio { get; set; }

        [Display(Name = "Hora Fin")]
        public Nullable<System.DateTime> DTFin { get; set; }

        [Display(Name = "Fecha de Registro")]
        public Nullable<System.DateTime> DTRegistro { get; set; }

        [Display(Name = "Autorizado")]
        public bool Estatus { get; set; }
    
        public virtual Salas Salas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
