//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaSalas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Salas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salas()
        {
            this.Reservacion = new HashSet<Reservacion>();
        }
    
        public int IDSala { get; set; }

        [Display(Name = "Area")]
        public int IDArea { get; set; }

        [Required(ErrorMessage = "Esta campo es Obligatorio")]
        [StringLength(100, ErrorMessage = "Este campo permite Maximo {1} caracteres")]
        [Display(Name = "Nombre de Sala")]
        public string DescSala { get; set; }

        [Display(Name = "Especificar Horario")]
        public bool EspecificaHorario { get; set; }

        [DataType(DataType.Time)]
        [Display(Name = "Horario Inicio")]
        public Nullable<System.TimeSpan> HoraInicial { get; set; }

        [DataType(DataType.Time)]
        [Display(Name = "Horario Final")]
        public Nullable<System.TimeSpan> HoraFinal { get; set; }

        [Display(Name = "Observaciones")]
        public string Observaciones { get; set; }
        public bool Estatus { get; set; }
    
        public virtual Areas Areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservacion> Reservacion { get; set; }
    }
}
