//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaSalas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;

    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Reservacion = new HashSet<Reservacion>();
        }
    
        public int IDUsuario { get; set; }
        
        [Display(Name = "Numero")]
        public Nullable<int> UsuarioNumeroExt { get; set; }

        [Required(ErrorMessage = "Esta campo es Obligatorio")]
        [StringLength(50, ErrorMessage = "Este campo permite Maximo {1} caracteres")]
        [Display(Name = "Nombre")]
        public string UsuarioNombre { get; set; }

        [Required(ErrorMessage = "Esta campo es Obligatorio")]
        [StringLength(40, ErrorMessage = "Este campo permite Maximo {1} caracteres")]
        [Display(Name = "Apellido P")]
        public string UsuarioApellido1 { get; set; }

        [StringLength(40, ErrorMessage = "Este campo permite Maximo {1} caracteres")]
        [Display(Name = "Apellido M")]
        public string UsuarioApellido2 { get; set; }

        [Required(ErrorMessage = "Esta campo es Obligatorio")]
        [StringLength(100, ErrorMessage = "Este campo permite Maximo {1} caracteres")]
        [EmailAddress(ErrorMessage = "Email invalido, ejemplo algo@ejemplo.com")]
        [Display(Name = "Email")]
        public string EmpleadoEmail { get; set; }

        [Required(ErrorMessage = "Esta campo es Obligatorio")]
        [StringLength(20, ErrorMessage = "Este campo permite Maximo {1} caracteres")]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string Pass { get; set; }

        [Required(ErrorMessage = "Esta campo es Obligatorio")]
        public int Tipo { get; set; }
        public bool Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservacion> Reservacion { get; set; }
    }
}
